version: '3.8'

services:
  fangdu-app:
    build: .
    container_name: fangdu-backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - HOST=0.0.0.0
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/database:/app/backend/database
      - ./backend/.env:/app/backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/materials"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加 Nginx 反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: fangdu-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - fangdu-app
  #   restart: unless-stopped

volumes:
  uploads:
  database:

networks:
  default:
    name: fangdu-network